name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true  # Enables Git LFS

      - name: Install Git LFS
        run: |
          sudo apt update
          sudo apt install git-lfs
          git lfs install

      - name: Configure Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"

      - name: Track Large Files with Git LFS
        run: |
          git lfs track "*.pkl" "*.keras"
          git add .gitattributes
          git commit -m "Track large files with Git LFS" || echo "No changes to commit"

      - name: Add Hugging Face Remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://user:${HF_TOKEN}@huggingface.co/spaces/gamerclub/pdf-assistant || echo "Remote already exists"

      - name: Pull from Hugging Face to Resolve Conflicts
        run: |
          git fetch hf
          git checkout main
          git reset --soft hf/main  # Use Hugging Face's latest version
          git add .
          git commit -m "Resolve conflicts with Hugging Face main branch" || echo "No conflicts to resolve"

      - name: Push to Hugging Face Spaces
        run: |
          git push hf main --force
